service: pushservice-api

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-east-1
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: any
          cors: true
  create:
    handler: push/register.create
    timeout: 20,
    description: Sends a push notification to android phones
    package:
      include:
        - node_modules
    events:
      - http:
          path: pushregister
          method: any
          cors: true
          integration: lambda
          request:
            template:
              application/json: '{ "deviceToken" : "$input.params(''deviceToken'')","subject" : "$input.params(''subject'')","message" : "$input.params(''message'')"}'
